### ISSUE TITLE
HTTPS problem

### ISSUE THREAD

**Issue by Atik-Ahamed** [leartgjoni/laravel-redis-chat#1]
the demo doesn't work with https . how can i make this project to also work with https connection

**Comment by leartgjoni** [comment]
In resources/views/conversation/show.blade.php change "http://127.0.0.1:8890" with "https://127.0.0.1:8890" also you must configure the node server to work on https

**Comment by Atik-Ahamed** [comment]
if you could provide a new update/commit of this project that would both work with https and http then it would be great.

**Comment by talhauddin** [comment]
Can you please provide the nodejs/server.js file of your demo https server.
Server is not working on HTTPS
