### ISSUE TITLE
Split chat commits from laravel installation

### ISSUE THREAD

**Issue by tylik1** [leartgjoni/laravel-redis-chat#5]
Hi
Thanks for the plugin. It would really be helpful if first commit was split in 2. 
The first is Laravel installation, while the second one, is everything related to your changes. 
Otherwise it is really hard to distinguish between your changes and Framework installation.

**Comment by leartgjoni** [comment]
It is actually a really good advise. Unfortunately this was a project built beforehand and afterwards I decided to make it public. One solution could be for you to install the framework, make a commit and after that copy my whole project to your directory. So you can see the changes by yourself

**Comment by tylik1** [comment]
that's a solution. Thanks
